"""
AI Food Recommendation Service — personalized, context-aware food suggestions
for Indian college students using Groq LLM (Llama 3.3 70B).

All food data is generated by the LLM from its real-world knowledge of restaurants
and eateries near Indian colleges. NO hardcoded fallback data.
Results are cached per user+meal-time in MongoDB with 6h TTL.
"""

import os
import json
import logging
from datetime import datetime, timezone, timedelta
from typing import Optional

from emergentintegrations.llm.chat import LlmChat, UserMessage, TextDelta, StreamDone

logger = logging.getLogger(__name__)

# ============ PROMPTS ============

FOOD_SYSTEM_PROMPT = """You are a food recommendation engine for Indian college students.
Given the user's context, suggest 6 REAL food places/options that actually exist near their location.

You must recommend real restaurants, dhabas, canteens, street food stalls, and eateries 
that are commonly found near Indian colleges in the specified city/area. Use your knowledge 
of popular student food spots, local chains, and common eatery types in that area.

Return a JSON array. Each item must have:
- name: REAL restaurant/stall name or realistic local eatery name for that area
- price: realistic cost in ₹ (integer) for a student meal there
- rating: 3.5-5.0 (float) - realistic rating
- distance: realistic distance from the college area (e.g. "0.3 km")
- tag: category (e.g. "North Indian", "South Indian", "Chinese", "Street Food", "Healthy", "Quick Bite", "Cafe")
- dietary: "veg", "non-veg", or "vegan"
- reason: 1-sentence why this is good for a student right now
- type: "restaurant" | "street_food" | "canteen" | "cafe" | "dhaba" | "mess"

Important:
- Recommend REAL places known to exist in or near the specified area
- If you know specific popular student spots in that city, name them
- Include a mix: some very cheap (₹30-50), some moderate (₹60-100), some slightly premium (₹100-150)
- Factor in the time of day for relevance
- For breakfast: suggest idli/dosa spots, tea stalls, paratha shops
- For lunch: suggest thalis, rice meals, combo meals
- For evening: suggest snack spots, chaats, momos
- For dinner: suggest budget restaurants, dhabas, mess options

Return ONLY valid JSON array, no markdown, no explanation."""

FOOD_USER_PROMPT = """Recommend 6 REAL food options for a {dietary} student near {location} \
with budget ₹{budget} per meal. It's currently {time_of_day}. \
They prefer: {cuisines}. \
Suggest actual restaurants, stalls, or food types commonly available in this area."""

# ============ REQUIRED FIELDS FOR VALIDATION ============

REQUIRED_FOOD_FIELDS = {"name", "price", "rating", "distance", "tag", "dietary", "reason"}


# ============ HELPERS ============

def _now_iso() -> str:
    """Return current UTC timestamp in ISO format."""
    return datetime.now(timezone.utc).isoformat()


def _iso_plus_hours(hours: int) -> str:
    """Return ISO timestamp for now + given hours."""
    return (datetime.now(timezone.utc) + timedelta(hours=hours)).isoformat()


def _get_time_of_day() -> str:
    """Determine the current meal time based on hour of day."""
    hour = datetime.now().hour
    if hour < 11:
        return "morning/breakfast"
    elif hour < 15:
        return "lunch"
    elif hour < 18:
        return "evening snack"
    else:
        return "dinner"


def matches_dietary(item_dietary: str, user_dietary: str) -> bool:
    """
    Check if a food item's dietary type matches the user's dietary preference.

    Matching logic:
    - "veg" users see: items with dietary "veg" or "vegan"
    - "vegan" users see: items with dietary "vegan" only
    - "non-veg" users see: all items
    - "any" users see: all items
    - "jain" users see: items with dietary "veg" or "vegan"
    """
    user_dietary = (user_dietary or "any").lower().strip()
    item_dietary = (item_dietary or "any").lower().strip()

    if user_dietary in ("non-veg", "any"):
        return True
    elif user_dietary == "vegan":
        return item_dietary == "vegan"
    elif user_dietary in ("veg", "jain"):
        return item_dietary in ("veg", "vegan")
    else:
        # Unknown preference — allow all
        return True


# ============ SERVICE ============

class FoodRecommendationService:
    """AI-powered food recommendation service for Indian college students."""

    def __init__(self, db):
        self.db = db

    async def get_recommendations(self, user_id: str) -> list[dict]:
        """
        Generate AI-powered food recommendations with user context.

        Orchestrates: context build → cache check → LLM call → filtering → cache store.
        On ANY exception: returns empty list (no hardcoded fallback).
        """
        try:
            # Step 1: Build context
            context = await self.build_context(user_id)

            dietary = context["dietary"]
            budget = context["budget_per_meal"]
            cuisines = context["cuisines"]
            location = context["location"]
            time_of_day = context["time_of_day"]

            # Step 2: Check cache
            cache_key = f"{user_id}_{time_of_day}_{dietary}"
            cached = await self._get_cached(cache_key)
            if cached is not None:
                return cached

            # Step 3: Query LLM for real food places
            prompt = FOOD_USER_PROMPT.format(
                dietary=dietary,
                location=location,
                budget=budget,
                time_of_day=time_of_day,
                cuisines=", ".join(cuisines) if cuisines else "any cuisine",
            )

            raw_response = await self._call_llm(prompt)

            # Step 4: Parse JSON response
            recommendations = json.loads(raw_response)

            if not isinstance(recommendations, list):
                logger.warning("LLM returned non-list response for food recommendations")
                return []

            # Step 5: Validate each item has required fields
            valid_items = [
                item for item in recommendations
                if isinstance(item, dict) and REQUIRED_FOOD_FIELDS.issubset(item.keys())
            ]

            # Step 6: Filter by budget
            valid_items = [
                item for item in valid_items
                if item.get("price", 999) <= budget
            ]

            # Step 7: Filter by dietary preference
            valid_items = [
                item for item in valid_items
                if matches_dietary(item.get("dietary", "any"), dietary)
            ]

            result = valid_items[:8]

            # Step 8: Cache results (6h TTL)
            await self._cache_result(cache_key, user_id, result)

            return result

        except Exception as e:
            logger.error(f"Food recommendation failed for user {user_id}: {e}")
            return []

    async def build_context(self, user_id: str) -> dict:
        """
        Gather user preferences, profile, and time context for food recommendations.

        Returns dict with: dietary, budget_per_meal, cuisines, location, time_of_day
        """
        # Fetch user food preferences
        prefs = await self.db.user_food_preferences.find_one({"user_id": user_id})

        # Fetch user profile for location
        profile = await self.db.users.find_one({"user_id": user_id})

        # Extract preference fields with defaults
        dietary = (prefs or {}).get("dietary", "any")
        budget_per_meal = (prefs or {}).get("budget_per_meal", 150)
        cuisines = (prefs or {}).get("cuisines", ["North Indian", "South Indian"])

        # Determine location from profile
        location = (
            (profile or {}).get("college")
            or (profile or {}).get("city")
            or "a college in India"
        )

        # Compute time of day
        time_of_day = _get_time_of_day()

        return {
            "dietary": dietary,
            "budget_per_meal": budget_per_meal,
            "cuisines": cuisines,
            "location": location,
            "time_of_day": time_of_day,
        }

    async def _call_llm(self, user_prompt: str) -> str:
        """Call Groq LLM and collect full response text for food recommendations."""
        api_key = os.getenv("GROQ_API_KEY", "")
        if not api_key:
            logger.warning("GROQ_API_KEY not set, cannot generate food recommendations")
            raise ValueError("GROQ_API_KEY not configured")

        llm = LlmChat(
            api_key=api_key,
            session_id="discover-food",
            system_message=FOOD_SYSTEM_PROMPT,
            temperature=0.5,
            max_tokens=2048,
            cache_enabled=True,
        ).with_model("groq", "llama-3.3-70b-versatile")

        full_text = ""
        async for event in llm.stream_message(UserMessage(text=user_prompt)):
            if isinstance(event, TextDelta):
                full_text += event.content
            elif isinstance(event, StreamDone):
                break

        # Handle markdown code blocks if LLM wraps response
        full_text = full_text.strip()
        if full_text.startswith("```"):
            lines = full_text.split("\n")
            lines = [line for line in lines if not line.strip().startswith("```")]
            full_text = "\n".join(lines)

        return full_text

    async def _get_cached(self, cache_key: str) -> Optional[list[dict]]:
        """Check food_recommendation_cache for valid cached results."""
        now = _now_iso()
        cached = await self.db.food_recommendation_cache.find_one({
            "cache_key": cache_key,
            "expires_at": {"$gt": now},
        })
        if cached:
            return cached.get("recommendations", [])
        return None

    async def _cache_result(self, cache_key: str, user_id: str, recommendations: list[dict]) -> None:
        """Store food recommendations in cache with 6h TTL."""
        try:
            await self.db.food_recommendation_cache.insert_one({
                "cache_key": cache_key,
                "user_id": user_id,
                "recommendations": recommendations,
                "created_at": _now_iso(),
                "expires_at": _iso_plus_hours(6),
            })
        except Exception as e:
            logger.error(f"Failed to cache food recommendations: {e}")
